// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzwS6R0RkWSgwSP8hA0HhlkCUxjnvWHsE',
    appId: '1:695379383052:web:82aa9e3eef7e81ab55ef29',
    messagingSenderId: '695379383052',
    projectId: 'dristi-dd785',
    authDomain: 'dristi-dd785.firebaseapp.com',
    storageBucket: 'dristi-dd785.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlZL6igPNJ4WOycFz6bMioK4uMFBu6h6k',
    appId: '1:695379383052:android:05e0e05a10cae75b55ef29',
    messagingSenderId: '695379383052',
    projectId: 'dristi-dd785',
    storageBucket: 'dristi-dd785.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVMbj-k_cyhfTB-zDXM3Qd0WJ2_1HE1xA',
    appId: '1:695379383052:ios:25160f196268818155ef29',
    messagingSenderId: '695379383052',
    projectId: 'dristi-dd785',
    storageBucket: 'dristi-dd785.firebasestorage.app',
    iosBundleId: 'com.example.drishtiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVMbj-k_cyhfTB-zDXM3Qd0WJ2_1HE1xA',
    appId: '1:695379383052:ios:25160f196268818155ef29',
    messagingSenderId: '695379383052',
    projectId: 'dristi-dd785',
    storageBucket: 'dristi-dd785.firebasestorage.app',
    iosBundleId: 'com.example.drishtiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzwS6R0RkWSgwSP8hA0HhlkCUxjnvWHsE',
    appId: '1:695379383052:web:f88bfdf1737115b955ef29',
    messagingSenderId: '695379383052',
    projectId: 'dristi-dd785',
    authDomain: 'dristi-dd785.firebaseapp.com',
    storageBucket: 'dristi-dd785.firebasestorage.app',
  );
}
